## Regression Models with Keras

In [3]:
!pip install pandas
import numpy as np
import pandas as pd
import keras

Collecting pandas
  Downloading pandas-1.4.1-cp38-cp38-win_amd64.whl (10.6 MB)
Requirement already satisfied: pytz>=2020.1 in c:\users\salaudeen ibrahim\anaconda3\envs\tensorflow_env\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.18.5 in c:\users\salaudeen ibrahim\anaconda3\envs\tensorflow_env\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\salaudeen ibrahim\anaconda3\envs\tensorflow_env\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\salaudeen ibrahim\anaconda3\envs\tensorflow_env\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: pandas
Successfully installed pandas-1.4.1

In [4]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [5]:
concrete_data.shape

(1030, 9)

In [6]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [8]:
# summing the null values
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [9]:
#Split data into predictor and target

concrete_data_columns = concrete_data.columns

In [10]:
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [12]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [13]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [14]:
predictors_norm = (predictors-predictors.mean())/predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [29]:
n_cols = predictors_norm.shape[1] # number of predictors

In [30]:
from keras.models import Sequential
from keras.layers import Dense

## Build a Neural Network

In [33]:
def regression_model():
    model = Sequential()
    model.add(Dense(50, activation ='relu', input_shape =(n_cols,)))
    model.add(Dense(50, activation = 'relu'))
    model.add(Dense(1))
    
    #compile model
    model.compile(optimizer = 'adam', loss= 'mean_squared_error')
    return model

The above function create a model that has two hidden layers, each of 50 hidden units.

## Train and Test the Network

In [34]:
model = regression_model()

#fit the model
model.fit(predictors_norm, target, validation_split = 0.3, epochs =100, verbose = 2)

Epoch 1/100
23/23 - 3s - loss: 1652.2618 - val_loss: 1137.1744
Epoch 2/100
23/23 - 0s - loss: 1520.1063 - val_loss: 1008.7106
Epoch 3/100
23/23 - 0s - loss: 1300.5869 - val_loss: 813.6255
Epoch 4/100
23/23 - 0s - loss: 981.0355 - val_loss: 567.9183
Epoch 5/100
23/23 - 0s - loss: 616.4804 - val_loss: 342.2553
Epoch 6/100
23/23 - 0s - loss: 347.8456 - val_loss: 206.8938
Epoch 7/100
23/23 - 0s - loss: 250.3377 - val_loss: 172.8331
Epoch 8/100
23/23 - 0s - loss: 229.8779 - val_loss: 167.1141
Epoch 9/100
23/23 - 0s - loss: 217.1547 - val_loss: 165.7544
Epoch 10/100
23/23 - 0s - loss: 206.6625 - val_loss: 162.9410
Epoch 11/100
23/23 - 0s - loss: 198.1635 - val_loss: 158.0666
Epoch 12/100
23/23 - 0s - loss: 191.1174 - val_loss: 156.0998
Epoch 13/100
23/23 - 0s - loss: 184.8470 - val_loss: 154.8001
Epoch 14/100
23/23 - 0s - loss: 179.1280 - val_loss: 156.1099
Epoch 15/100
23/23 - 0s - loss: 174.6066 - val_loss: 151.6638
Epoch 16/100
23/23 - 0s - loss: 170.4316 - val_loss: 150.8949
Epoch 17/100
23/23 - 0s - loss: 166.5720 - val_loss: 149.2713
Epoch 18/100
23/23 - 0s - loss: 163.7368 - val_loss: 146.9317
Epoch 19/100
23/23 - 0s - loss: 160.5555 - val_loss: 147.6724
Epoch 20/100
23/23 - 0s - loss: 157.8831 - val_loss: 145.3159
Epoch 21/100
23/23 - 0s - loss: 155.0428 - val_loss: 144.8183
Epoch 22/100
23/23 - 0s - loss: 153.4794 - val_loss: 145.3758
Epoch 23/100
23/23 - 0s - loss: 150.7961 - val_loss: 143.6625
Epoch 24/100
23/23 - 0s - loss: 149.0215 - val_loss: 142.5068
Epoch 25/100
23/23 - 0s - loss: 147.3809 - val_loss: 141.2911
Epoch 26/100
23/23 - 0s - loss: 146.2569 - val_loss: 141.0762
Epoch 27/100
23/23 - 0s - loss: 145.3757 - val_loss: 139.7164
Epoch 28/100
23/23 - 0s - loss: 143.1309 - val_loss: 140.0376
Epoch 29/100
23/23 - 0s - loss: 141.6899 - val_loss: 141.2682
Epoch 30/100
23/23 - 0s - loss: 141.0694 - val_loss: 143.0280
Epoch 31/100
23/23 - 0s - loss: 139.0900 - val_loss: 139.4481
Epoch 32/100
23/23 - 0s - loss: 137.8501 - val_loss: 138.7576
Epoch 33/100
23/23 - 0s - loss: 136.6219 - val_loss: 139.3997
Epoch 34/100
23/23 - 0s - loss: 135.6877 - val_loss: 139.5589
Epoch 35/100
23/23 - 0s - loss: 134.5575 - val_loss: 140.5851
Epoch 36/100
23/23 - 0s - loss: 134.5815 - val_loss: 138.2452
Epoch 37/100
23/23 - 0s - loss: 131.9508 - val_loss: 140.6783
Epoch 38/100
23/23 - 0s - loss: 130.7316 - val_loss: 139.6978
Epoch 39/100
23/23 - 0s - loss: 129.5568 - val_loss: 140.9073
Epoch 40/100
23/23 - 0s - loss: 128.9434 - val_loss: 141.5086
Epoch 41/100
23/23 - 0s - loss: 128.2502 - val_loss: 141.3214
Epoch 42/100
23/23 - 0s - loss: 125.9255 - val_loss: 140.9361
Epoch 43/100
23/23 - 0s - loss: 125.3405 - val_loss: 140.5945
Epoch 44/100
23/23 - 0s - loss: 125.0706 - val_loss: 141.8246
Epoch 45/100
23/23 - 0s - loss: 122.8013 - val_loss: 139.4099
Epoch 46/100
23/23 - 0s - loss: 121.3514 - val_loss: 142.9584
Epoch 47/100
23/23 - 0s - loss: 119.7721 - val_loss: 141.3756
Epoch 48/100
23/23 - 0s - loss: 118.6636 - val_loss: 142.3195
Epoch 49/100
23/23 - 0s - loss: 117.6594 - val_loss: 141.1088
Epoch 50/100
23/23 - 0s - loss: 116.0556 - val_loss: 142.3434
Epoch 51/100
23/23 - 0s - loss: 114.9071 - val_loss: 143.0517
Epoch 52/100
23/23 - 0s - loss: 113.8417 - val_loss: 144.0887
Epoch 53/100
23/23 - 0s - loss: 113.4282 - val_loss: 143.0482
Epoch 54/100
23/23 - 0s - loss: 111.1863 - val_loss: 138.0757
Epoch 55/100
23/23 - 0s - loss: 109.1960 - val_loss: 140.5980
Epoch 56/100
23/23 - 0s - loss: 107.4650 - val_loss: 135.6031
Epoch 57/100
23/23 - 0s - loss: 105.7090 - val_loss: 139.2200
Epoch 58/100
23/23 - 0s - loss: 103.3696 - val_loss: 139.4507
Epoch 59/100
23/23 - 0s - loss: 102.7786 - val_loss: 137.7029
Epoch 60/100
23/23 - 0s - loss: 99.6174 - val_loss: 134.7288
Epoch 61/100
23/23 - 0s - loss: 98.1025 - val_loss: 135.2838
Epoch 62/100
23/23 - 0s - loss: 95.6239 - val_loss: 133.2907
Epoch 63/100
23/23 - 0s - loss: 94.1407 - val_loss: 129.3429
Epoch 64/100
23/23 - 0s - loss: 92.7877 - val_loss: 134.6969
Epoch 65/100
23/23 - 0s - loss: 89.7045 - val_loss: 125.8495
Epoch 66/100
23/23 - 0s - loss: 87.0618 - val_loss: 126.8136
Epoch 67/100
23/23 - 0s - loss: 85.1169 - val_loss: 120.5587
Epoch 68/100
23/23 - 0s - loss: 82.6396 - val_loss: 127.2849
Epoch 69/100
23/23 - 0s - loss: 80.6077 - val_loss: 117.4842
Epoch 70/100
23/23 - 0s - loss: 76.8985 - val_loss: 114.0790
Epoch 71/100
23/23 - 0s - loss: 75.3320 - val_loss: 114.7250
Epoch 72/100
23/23 - 0s - loss: 72.7576 - val_loss: 112.2334
Epoch 73/100
23/23 - 0s - loss: 69.6553 - val_loss: 111.5438
Epoch 74/100
23/23 - 0s - loss: 68.0289 - val_loss: 107.8731
Epoch 75/100
23/23 - 0s - loss: 66.2424 - val_loss: 107.8675
Epoch 76/100
23/23 - 0s - loss: 64.0474 - val_loss: 101.7128
Epoch 77/100
23/23 - 0s - loss: 61.2975 - val_loss: 105.8642
Epoch 78/100
23/23 - 0s - loss: 60.2044 - val_loss: 99.3979
Epoch 79/100
23/23 - 0s - loss: 58.2245 - val_loss: 98.7785
Epoch 80/100
23/23 - 0s - loss: 57.5158 - val_loss: 102.2145
Epoch 81/100
23/23 - 0s - loss: 54.8093 - val_loss: 95.0135
Epoch 82/100
23/23 - 0s - loss: 53.6775 - val_loss: 99.4142
Epoch 83/100
23/23 - 0s - loss: 53.0788 - val_loss: 94.0716
Epoch 84/100
23/23 - 0s - loss: 52.0834 - val_loss: 89.7272
Epoch 85/100
23/23 - 0s - loss: 50.5522 - val_loss: 92.8663
Epoch 86/100
23/23 - 0s - loss: 49.6356 - val_loss: 87.0035
Epoch 87/100
23/23 - 0s - loss: 48.2555 - val_loss: 92.0222
Epoch 88/100
23/23 - 0s - loss: 47.5276 - val_loss: 90.1715
Epoch 89/100
23/23 - 0s - loss: 46.5023 - val_loss: 86.5142
Epoch 90/100
23/23 - 0s - loss: 46.2792 - val_loss: 86.8839
Epoch 91/100
23/23 - 0s - loss: 44.3189 - val_loss: 86.6672
Epoch 92/100
23/23 - 0s - loss: 43.9788 - val_loss: 86.0688
Epoch 93/100
23/23 - 0s - loss: 43.6393 - val_loss: 83.7394
Epoch 94/100
23/23 - 0s - loss: 42.7803 - val_loss: 87.0628
Epoch 95/100
23/23 - 0s - loss: 41.9754 - val_loss: 81.1866
Epoch 96/100
23/23 - 0s - loss: 41.7310 - val_loss: 82.1356
Epoch 97/100
23/23 - 0s - loss: 40.9727 - val_loss: 83.3309
Epoch 98/100
23/23 - 0s - loss: 40.3025 - val_loss: 93.4747
Epoch 99/100
23/23 - 0s - loss: 41.2721 - val_loss: 82.1433
Epoch 100/100
23/23 - 0s - loss: 39.9990 - val_loss: 76.5398